In [1]:
import numpy as np

In [15]:
#kronecker delta function
def kron_delta(i,j):
  if i==j:
    return 1.0
  else:
    return 0.0
#Converts T_A(B)=AB to 4th order tensor
#Make it more efficient by looping only over l==j.
def l_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for i in range(0,n+1):
      for j in range(0,n+1):
        for k in range(0,n+1):
          for l in range(0,n+1):
              C[i,j,k,l]=A[i,k]*kron_delta(l,j)
    return C
#Converts T_A(B)=BA to 4th order tensor
#Make it more efficient by looping only over l==j.
def r_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for i in range(0,n+1):
      for j in range(0,n+1):
        for k in range(0,n+1):
          for l in range(0,n+1):
              C[i,j,k,l]=A[l,j]*kron_delta(i,k)
    return C
#Converts right operator to 4th order tensor
def tensor2matrix(C):
    n=np.shape(A)[0]-1
    C = np.reshape(C,((n+1)**2,(n+1)**2))
    return C
def l_operator2matrix(A):
    C = l_operator2tensor(A)
    C = tensor2matrix(C)
    return C
def r_operator2matrix(A):
    C = r_operator2tensor(A)
    C = tensor2matrix(C)
    return C

## The efficient version

In [12]:
def l_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for i in range(0,n+1):
        for j in range(0,n+1):
            for k in range(0,n+1):
                C[i,j,k,j]=A[i,k]
    return C
#Converts T_A(B)=BA to 4th order tensor
#Make it more efficient by looping only over l==j.
def r_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for j in range(0,n+1):
        for i in range(0,n+1):
            for l in range(0,n+1):
                C[i,j,i,l]=A[l,j]
    return C

In [24]:
n=2
A = np.arange(1,n**2+1)
A = np.reshape(A,(n,n))
print(A)
print(l_operator2matrix(A))

[[1 2]
 [3 4]]
[[1. 0. 2. 0.]
 [0. 1. 0. 2.]
 [3. 0. 4. 0.]
 [0. 3. 0. 4.]]
