In [1]:
import numpy as np

To convert left and right action operators $T_A(B) = AB, U_A(B) = BA$ into a matrix, we convert it to a fourth order tensor and then use `np.shape` to make it into a matrix. First, we have an inefficient readable version and then the efficient version.

In [38]:
#kronecker delta function
def kron_delta(i,j):
  if i==j:
    return 1.0
  else:
    return 0.0
#Converts T_A(B)=AB to 4th order tensor
#Make it more efficient by looping only over l==j.
def l_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for i in range(0,n+1):
      for j in range(0,n+1):
        for k in range(0,n+1):
          for l in range(0,n+1):
              C[i,j,k,l]=A[i,k]*kron_delta(l,j)
    return C
#Converts T_A(B)=BA to 4th order tensor
#Make it more efficient by looping only over l==j.
def r_operator2tensor(A):
    n=np.shape(A)[0]-1
    C = np.zeros(((n+1),(n+1),(n+1),(n+1)))
    for i in range(0,n+1):
      for j in range(0,n+1):
        for k in range(0,n+1):
          for l in range(0,n+1):
              C[i,j,k,l]=A[l,j]*kron_delta(i,k)
    return C
#Converts right operator to 4th order tensor
def tensor2matrix(C):
    n=np.shape(A)[0]-1
    C = np.reshape(C,((n+1)**2,(n+1)**2))
    return C
def l_operator2matrix(A):
    C = l_operator2tensor(A)
    C = tensor2matrix(C)
    return C
def r_operator2matrix(A):
    C = r_operator2tensor(A)
    C = tensor2matrix(C)
    return C

# Efficient version

In [39]:
#Converts T_A(B)=AB to 4th order tensor
def l_operator2tensor(A):
    n   = np.shape(A)[0]
    C   = np.zeros((n,n,n,n))
    diag= np.arange(0,n)
    C[:,diag,:,diag]=A[:,:] #C to be updated for j=l
    return C
#Converts T_A(B)=BA to 4th order tensor
def r_operator2tensor(A):
    n   = np.shape(A)[0]
    C   = np.zeros((n,n,n,n))
    diag=np.arange(0,n)
    C[diag,:,diag,:]=A.T[:,:]
    return C
def tensor2matrix(C):
    n = np.shape(A)[0]
    C = np.reshape(C,(n**2,n**2))
    return C
def l_operator2matrix(A):
    C = l_operator2tensor(A)
    C = tensor2matrix(C)
    return C
def r_operator2matrix(A):
    C = r_operator2tensor(A)
    C = tensor2matrix(C)
    return C

In [42]:
n = 2
A = np.arange(1,n**2+1)
A = np.reshape(A,((n,n)))
print(A)
print(l_operator2matrix(A))
print(r_operator2matrix(A))

[[1 2]
 [3 4]]
[[1. 0. 2. 0.]
 [0. 1. 0. 2.]
 [3. 0. 4. 0.]
 [0. 3. 0. 4.]]
[[1. 3. 0. 0.]
 [2. 4. 0. 0.]
 [0. 0. 1. 3.]
 [0. 0. 2. 4.]]


This approach is still inefficient in our case because we can see a very clear pattern in the output. We should prove that pattern and use it to create these matrices. 